import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Trial app',
  description: 'Generated by MARVIN IDIBIA',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="headtop"><span>🎮</span>Games</div>
        <nav>
        <Link className='nav' href="/">Home</Link>
        <Link className='nav' href="/genre">Genre</Link>
        <Link className='nav' href="/history">Game History</Link>
        <Link className='nav' href="/settings">Settings</Link>
        <button className='but'>X</button>
        </nav>
        {children}
      </body>
    </html>
  )
}
